version: '2'
services:
  db:
    container_name: ndb
    build: ./db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    #restart: always
    # volumes:
    #   - ./db/mysql_data:/var/lib/mysql
  web:
    container_name: nweb
    build: ./web
    ports:
      - '8080:80'
    depends_on:
      - db
    tty: true
    #restart: always
    # volumes:
    #   - ../game_information:/var/www/html/game_information:cached